FROM node:18-alpine As production

WORKDIR /usr/src/app

COPY --chown=node:node package*.json ./

COPY --chown=node:node . .

RUN yarn install --immutable --immutable-cache --check-cache

RUN yarn build

ENV NODE_ENV production

CMD [ "node", "dist/main.js" ]
