### 유저 생성
POST {{domain}}/api/auth/signup
Content-Type: application/json

{
  "email": "test2@test.com",
  "password": "12345678",
  "nickname": "test2"
}

### 유저 로그인
POST {{domain}}/api/auth/login
Content-Type: application/json

{
  "email": "test2@test.com",
  "password": "12345678"
}

### 이메일 중복 체크
GET {{domain}}/api/users/exists?email=asdasddd@dfss.com

### 유저 삭제
DELETE {{domain}}/api/users/2
Authorization: Bearer {{accessToken}}

### 관리자 생성
POST {{domain}}/api/auth/signup
Content-Type: application/json

{
  "email": "admin@admin.com",
  "password": "111122223333",
  "nickname": "test2",
  "isAdmin": true
}

### 관리자 로그인
POST {{domain}}/api/auth/login
Content-Type: application/json

{
  "email": "admin@admin.com",
  "password": "111122223333"
}

### Refresh Test
POST {{domain}}/api/auth/refresh
Content-Type: application/json

{
  "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiZW1haWwiOiJhc2Rhc2RkZEBkZnNzLmNvbSIsIm5pY2tuYW1lIjoidGVzdDIiLCJyb2xlIjoidXNlciIsImlhdCI6MTY4MTUzMjg1MCwiZXhwIjoxNjgyNzQyNDUwfQ.bIMYfrvi66c4hc0AO49J08kUoqvVNYB71UKGHTDbAdc"
}

### jwt test
GET {{domain}}/api/auth/jwtTest
Authorization: Bearer {{accessToken}}

### role test User
GET {{domain}}/api/auth/roleTest
Authorization: Bearer {{accessToken}}

### role test ADMIN
GET {{domain}}/api/auth/roleTest
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MiwiZW1haWwiOiJhZG1pbkBhZG1pbi5jb20iLCJuaWNrbmFtZSI6InRlc3QyIiwicm9sZSI6ImFkbWluIiwiaWF0IjoxNjgwNjg5ODk4LCJleHAiOjE2ODA3NzYyOTh9.0RgGsbkmNTjVwf7Nq0oLYOQSgoLEq6wNymaF6Agugrg

### email 인증
GET {{domain}}/api/auth/send-email-verification
Authorization: Bearer {{accessToken}}
